export interface Puzzle {
  id: number
  block: 'a' | 'b' | 'c' | 'd'
  type: 'filled' | 'unfilled'
  column: 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j'
}

export interface PuzzleProps {
  a: Puzzle[]
  b: Puzzle[]
  c: Puzzle[]
  d: Puzzle[]
}
export const gamePuzzle: PuzzleProps = {
  a: [
    {
      id: 1,
      block: 'a',
      type: 'unfilled',
      column: 'a',
    },
    {
      id: 2,
      block: 'a',
      type: 'unfilled',
      column: 'b',
    },
    {
      id: 3,
      block: 'a',
      type: 'unfilled',
      column: 'c',
    },
    {
      id: 4,
      block: 'a',
      type: 'unfilled',
      column: 'd',
    },
    {
      id: 5,
      block: 'a',
      type: 'filled',
      column: 'e',
    },
    {
      id: 11,
      block: 'a',
      type: 'unfilled',
      column: 'a',
    },
    {
      id: 12,
      block: 'a',
      type: 'unfilled',
      column: 'b',
    },
    {
      id: 13,
      block: 'a',
      type: 'unfilled',
      column: 'c',
    },
    {
      id: 14,
      block: 'a',
      type: 'filled',
      column: 'd',
    },
    {
      id: 15,
      block: 'a',
      type: 'filled',
      column: 'e',
    },
    {
      id: 21,
      block: 'a',
      type: 'filled',
      column: 'a',
    },
    {
      id: 22,
      block: 'a',
      type: 'filled',
      column: 'b',
    },
    {
      id: 23,
      block: 'a',
      type: 'unfilled',
      column: 'c',
    },
    {
      id: 24,
      block: 'a',
      type: 'filled',
      column: 'd',
    },
    {
      id: 25,
      block: 'a',
      type: 'filled',
      column: 'e',
    },
    {
      id: 31,
      block: 'a',
      type: 'filled',
      column: 'a',
    },
    {
      id: 32,
      block: 'a',
      type: 'filled',
      column: 'b',
    },
    {
      id: 33,
      block: 'a',
      type: 'filled',
      column: 'c',
    },
    {
      id: 34,
      block: 'a',
      type: 'filled',
      column: 'd',
    },
    {
      id: 35,
      block: 'a',
      type: 'filled',
      column: 'e',
    },
    {
      id: 41,
      block: 'a',
      type: 'filled',
      column: 'a',
    },
    {
      id: 42,
      block: 'a',
      type: 'filled',
      column: 'b',
    },
    {
      id: 43,
      block: 'a',
      type: 'filled',
      column: 'c',
    },
    {
      id: 44,
      block: 'a',
      type: 'filled',
      column: 'd',
    },
    {
      id: 45,
      block: 'a',
      type: 'filled',
      column: 'e',
    },
  ],
  b: [
    {
      id: 6,
      block: 'b',
      type: 'filled',
      column: 'f',
    },
    {
      id: 7,
      block: 'b',
      type: 'unfilled',
      column: 'g',
    },
    {
      id: 8,
      block: 'b',
      type: 'unfilled',
      column: 'h',
    },
    {
      id: 9,
      block: 'b',
      type: 'unfilled',
      column: 'i',
    },
    {
      id: 10,
      block: 'b',
      type: 'unfilled',
      column: 'j',
    },
    {
      id: 16,
      block: 'b',
      type: 'filled',
      column: 'f',
    },
    {
      id: 17,
      block: 'b',
      type: 'filled',
      column: 'g',
    },
    {
      id: 18,
      block: 'b',
      type: 'unfilled',
      column: 'h',
    },
    {
      id: 19,
      block: 'b',
      type: 'unfilled',
      column: 'i',
    },
    {
      id: 20,
      block: 'b',
      type: 'unfilled',
      column: 'j',
    },
    {
      id: 26,
      block: 'b',
      type: 'filled',
      column: 'f',
    },
    {
      id: 27,
      block: 'b',
      type: 'filled',
      column: 'g',
    },
    {
      id: 28,
      block: 'b',
      type: 'unfilled',
      column: 'h',
    },
    {
      id: 29,
      block: 'b',
      type: 'filled',
      column: 'i',
    },
    {
      id: 30,
      block: 'b',
      type: 'filled',
      column: 'j',
    },
    {
      id: 36,
      block: 'b',
      type: 'filled',
      column: 'f',
    },
    {
      id: 37,
      block: 'b',
      type: 'filled',
      column: 'g',
    },
    {
      id: 38,
      block: 'b',
      type: 'filled',
      column: 'h',
    },
    {
      id: 39,
      block: 'b',
      type: 'filled',
      column: 'i',
    },
    {
      id: 40,
      block: 'b',
      type: 'filled',
      column: 'j',
    },
    {
      id: 46,
      block: 'b',
      type: 'filled',
      column: 'f',
    },
    {
      id: 47,
      block: 'b',
      type: 'filled',
      column: 'g',
    },
    {
      id: 48,
      block: 'b',
      type: 'filled',
      column: 'h',
    },
    {
      id: 49,
      block: 'b',
      type: 'filled',
      column: 'i',
    },
    {
      id: 50,
      block: 'b',
      type: 'filled',
      column: 'j',
    },
  ],
  c: [
    {
      id: 51,
      block: 'c',
      type: 'unfilled',
      column: 'a',
    },
    {
      id: 52,
      block: 'c',
      type: 'filled',
      column: 'b',
    },
    {
      id: 53,
      block: 'c',
      type: 'filled',
      column: 'c',
    },
    {
      id: 54,
      block: 'c',
      type: 'filled',
      column: 'd',
    },
    {
      id: 55,
      block: 'c',
      type: 'filled',
      column: 'e',
    },
    {
      id: 61,
      block: 'c',
      type: 'unfilled',
      column: 'a',
    },
    {
      id: 62,
      block: 'c',
      type: 'unfilled',
      column: 'b',
    },
    {
      id: 63,
      block: 'c',
      type: 'filled',
      column: 'c',
    },
    {
      id: 64,
      block: 'c',
      type: 'filled',
      column: 'd',
    },
    {
      id: 65,
      block: 'c',
      type: 'filled',
      column: 'e',
    },
    {
      id: 71,
      block: 'c',
      type: 'unfilled',
      column: 'a',
    },
    {
      id: 72,
      block: 'c',
      type: 'filled',
      column: 'b',
    },
    {
      id: 73,
      block: 'c',
      type: 'filled',
      column: 'c',
    },
    {
      id: 74,
      block: 'c',
      type: 'filled',
      column: 'd',
    },
    {
      id: 75,
      block: 'c',
      type: 'filled',
      column: 'e',
    },
    {
      id: 81,
      block: 'c',
      type: 'unfilled',
      column: 'a',
    },
    {
      id: 82,
      block: 'c',
      type: 'unfilled',
      column: 'b',
    },
    {
      id: 83,
      block: 'c',
      type: 'unfilled',
      column: 'c',
    },
    {
      id: 84,
      block: 'c',
      type: 'unfilled',
      column: 'd',
    },
    {
      id: 85,
      block: 'c',
      type: 'filled',
      column: 'e',
    },
    {
      id: 91,
      block: 'c',
      type: 'unfilled',
      column: 'a',
    },
    {
      id: 92,
      block: 'c',
      type: 'unfilled',
      column: 'b',
    },
    {
      id: 93,
      block: 'c',
      type: 'unfilled',
      column: 'c',
    },
    {
      id: 94,
      block: 'c',
      type: 'unfilled',
      column: 'd',
    },
    {
      id: 95,
      block: 'c',
      type: 'filled',
      column: 'e',
    },
  ],
  d: [
    {
      id: 56,
      block: 'd',
      type: 'filled',
      column: 'f',
    },
    {
      id: 57,
      block: 'd',
      type: 'filled',
      column: 'g',
    },
    {
      id: 58,
      block: 'd',
      type: 'filled',
      column: 'h',
    },
    {
      id: 59,
      block: 'd',
      type: 'filled',
      column: 'i',
    },
    {
      id: 60,
      block: 'd',
      type: 'unfilled',
      column: 'j',
    },
    {
      id: 66,
      block: 'd',
      type: 'filled',
      column: 'f',
    },
    {
      id: 67,
      block: 'd',
      type: 'filled',
      column: 'g',
    },
    {
      id: 68,
      block: 'd',
      type: 'filled',
      column: 'h',
    },
    {
      id: 69,
      block: 'd',
      type: 'unfilled',
      column: 'i',
    },
    {
      id: 70,
      block: 'd',
      type: 'unfilled',
      column: 'j',
    },
    {
      id: 76,
      block: 'd',
      type: 'filled',
      column: 'f',
    },
    {
      id: 77,
      block: 'd',
      type: 'filled',
      column: 'g',
    },
    {
      id: 78,
      block: 'd',
      type: 'filled',
      column: 'h',
    },
    {
      id: 79,
      block: 'd',
      type: 'filled',
      column: 'i',
    },
    {
      id: 80,
      block: 'd',
      type: 'unfilled',
      column: 'j',
    },
    {
      id: 86,
      block: 'd',
      type: 'filled',
      column: 'f',
    },
    {
      id: 87,
      block: 'd',
      type: 'unfilled',
      column: 'g',
    },
    {
      id: 88,
      block: 'd',
      type: 'unfilled',
      column: 'h',
    },
    {
      id: 89,
      block: 'd',
      type: 'unfilled',
      column: 'i',
    },
    {
      id: 90,
      block: 'd',
      type: 'unfilled',
      column: 'j',
    },
    {
      id: 96,
      block: 'd',
      type: 'filled',
      column: 'f',
    },
    {
      id: 97,
      block: 'd',
      type: 'unfilled',
      column: 'g',
    },
    {
      id: 98,
      block: 'd',
      type: 'unfilled',
      column: 'h',
    },
    {
      id: 99,
      block: 'd',
      type: 'unfilled',
      column: 'i',
    },
    {
      id: 100,
      block: 'd',
      type: 'unfilled',
      column: 'j',
    },
  ],
}
